--[[
Always Run Localization by Web_Artur [steamID64 76561198115550963]
This file contains localization strings for the Always Run addon in various languages.
]]--

return {
    en = {
        always_run_enabled = "Enable Always Run",
        utilities_server = "Server",
        always_run_menu = "Always Run",
        always_run_description = "When enabled, your character will always run unless you hold ALT or SHIFT to walk.",
        always_run_capslock_hint = "Assign any key to toggle always run.",
        always_run_github = "Open GitHub repository",
        always_run_press_key_hint = "Press the desired key to toggle always run...",
        always_run_key_selected = "Key selected: ",
        always_run_key = "Key: ",
        always_run_mute_sound = "Mute toggle sound",
        always_run_select_key_hint = "Click to select a new key for always run",
        always_run_custom_key_enable = "Enable custom toggle key",
        always_run_key_cancelled = "Key assignment cancelled."
    },
    fr = {
        always_run_enabled = "Activer la course automatique",
        utilities_server = "Serveur",
        always_run_menu = "Course automatique",
        always_run_description = "Lorsque activé, votre personnage courra toujours sauf si vous maintenez ALT ou SHIFT pour marcher.",
        always_run_capslock_hint = "Attribuez une touche pour activer/désactiver la course automatique.",
        always_run_github = "Ouvrir le dépôt GitHub",
        always_run_press_key_hint = "Appuyez sur la touche souhaitée pour la course automatique...",
        always_run_key_selected = "Touche sélectionnée : ",
        always_run_key = "Touche : ",
        always_run_key_cancelled = "Attribution de la touche annulée."
    },
    de = {
        always_run_enabled = "Automatisches Laufen aktivieren",
        utilities_server = "Server",
        always_run_menu = "Automatisches Laufen",
        always_run_description = "Wenn aktiviert, läuft dein Charakter immer, es sei denn, du hältst ALT oder SHIFT, um zu gehen.",
        always_run_capslock_hint = "Weise eine beliebige Taste zum Umschalten des automatischen Laufens zu.",
        always_run_github = "GitHub-Repository öffnen",
        always_run_press_key_hint = "Drücke die gewünschte Taste für automatisches Laufen...",
        always_run_key_selected = "Ausgewählte Taste: ",
        always_run_key = "Taste: ",
        always_run_key_cancelled = "Tastenbelegung abgebrochen."
    },
    ru = {
        always_run_enabled = "Включить постоянный бег",
        utilities_server = "Сервер",
        always_run_menu = "Постоянный бег",
        always_run_description = "Когда включено, ваш персонаж всегда будет бежать, если вы не удерживаете ALT или SHIFT для ходьбы.",
        always_run_capslock_hint = "Назначьте любую клавишу для переключения автобега.",
        always_run_github = "Открыть GitHub репозиторий",
        always_run_press_key_hint = "Нажмите желаемую клавишу для переключения автобега...",
        always_run_key_selected = "Клавиша выбрана: ",
        always_run_key = "Клавиша: ",
        always_run_mute_sound = "Отключить звук переключения",
        always_run_select_key_hint = "Нажмите, чтобы выбрать новую клавишу для автобега",
        always_run_custom_key_enable = "Включить пользовательскую клавишу",
        always_run_key_cancelled = "Назначение клавиши отменено."
    },
    es = {
        always_run_enabled = "Habilitar carrera automática",
        utilities_server = "Servidor",
        always_run_menu = "Carrera automática",
        always_run_description = "Cuando está habilitado, tu personaje siempre correrá a menos que mantengas ALT o SHIFT para caminar.",
        always_run_capslock_hint = "Asigna cualquier tecla para alternar la carrera automática.",
        always_run_github = "Abrir repositorio de GitHub",
        always_run_press_key_hint = "Presiona la tecla deseada para alternar la carrera automática...",
        always_run_key_selected = "Tecla seleccionada: ",
        always_run_key = "Tecla: ",
        always_run_key_cancelled = "Asignación de tecla cancelada."
    },
    zh_CN = {
        always_run_enabled = "启用自动奔跑",
        utilities_server = "服务器",
        always_run_menu = "自动奔跑",
        always_run_description = "启用后，您的角色将始终奔跑，除非您按住 ALT 或 SHIFT 以步行。",
        always_run_capslock_hint = "分配任意键以切换自动奔跑。",
        always_run_github = "打开 GitHub 仓库",
        always_run_press_key_hint = "按下所需的按键以切换自动奔跑...",
        always_run_key_selected = "已选择按键：",
        always_run_key = "按键：",
        always_run_key_cancelled = "按键分配已取消。"
    },
    zh_TW = {
        always_run_enabled = "啟用自動奔跑",
        utilities_server = "伺服器",
        always_run_menu = "自動奔跑",
        always_run_description = "啟用後，您的角色將始終奔跑，除非您按住 ALT 或 SHIFT 以步行。",
        always_run_capslock_hint = "分配任意按鍵以切換自動奔跑。",
        always_run_github = "開啟 GitHub 儲存庫",
        always_run_press_key_hint = "按下想要的按鍵以切換自動奔跑...",
        always_run_key_selected = "已選擇按鍵：",
        always_run_key = "按鍵：",
        always_run_key_cancelled = "按鍵指派已取消。"
    },
    ko = {
        always_run_enabled = "자동 달리기 활성화",
        utilities_server = "서버",
        always_run_menu = "자동 달리기",
        always_run_description = "활성화되면 ALT 또는 SHIFT를 눌러 걷지 않는 한 캐릭터가 항상 달립니다.",
        always_run_capslock_hint = "자동 달리기 토글 키를 지정하세요.",
        always_run_github = "GitHub 저장소 열기",
        always_run_press_key_hint = "자동 달리기 토글 키를 누르세요...",
        always_run_key_selected = "선택된 키: ",
        always_run_key = "키: ",
        always_run_key_cancelled = "키 지정이 취소되었습니다."
    },
    ja = {
        always_run_enabled = "常時走るを有効にする",
        utilities_server = "サーバー",
        always_run_menu = "常時走る",
        always_run_description = "有効にすると、ALT または SHIFT を押して歩かない限り、キャラクターは常に走ります。",
        always_run_capslock_hint = "常時走るの切り替えキーを割り当ててください。",
        always_run_github = "GitHubリポジトリを開く",
        always_run_press_key_hint = "常時走るの切り替え用キーを押してください...",
        always_run_key_selected = "選択されたキー: ",
        always_run_key = "キー: ",
        always_run_key_cancelled = "キーの割り当てがキャンセルされました。"
    },
    pl = {
        always_run_enabled = "Włącz automatyczne bieganie",
        utilities_server = "Serwer",
        always_run_menu = "Automatyczne bieganie",
        always_run_description = "Gdy włączone, twoja postać zawsze będzie biegać, chyba że przytrzymasz ALT lub SHIFT, aby chodzić.",
        always_run_capslock_hint = "Przypisz dowolny klawisz do przełączania automatycznego biegania.",
        always_run_github = "Otwórz repozytorium GitHub",
        always_run_press_key_hint = "Naciśnij wybrany klawisz do przełączania biegania...",
        always_run_key_selected = "Wybrany klawisz: ",
        always_run_key = "Klawisz: ",
        always_run_key_cancelled = "Przypisanie klawisza anulowane."
    },
    pt = {
        always_run_enabled = "Ativar corrida automática",
        utilities_server = "Servidor",
        always_run_menu = "Corrida automática",
        always_run_description = "Quando ativado, seu personagem sempre correrá, a menos que você mantenha ALT ou SHIFT para andar.",
        always_run_capslock_hint = "Atribua qualquer tecla para alternar a corrida automática.",
        always_run_github = "Abrir repositório do GitHub",
        always_run_press_key_hint = "Pressione a tecla desejada para alternar a corrida automática...",
        always_run_key_selected = "Tecla selecionada: ",
        always_run_key = "Tecla: ",
        always_run_key_cancelled = "Atribuição de tecla cancelada."
    },
    tr = {
        always_run_enabled = "Sürekli Koşmayı Etkinleştir",
        utilities_server = "Sunucu",
        always_run_menu = "Sürekli Koşma",
        always_run_description = "Etkinleştirildiğinde, ALT veya SHIFT tuşuna basmadığınız sürece karakteriniz her zaman koşar.",
        always_run_capslock_hint = "Sürekli koşmayı açıp kapatmak için bir tuş atayın.",
        always_run_github = "GitHub deposunu aç",
        always_run_press_key_hint = "Sürekli koşma için istediğiniz tuşa basın...",
        always_run_key_selected = "Seçilen tuş: ",
        always_run_key = "Tuş: ",
        always_run_key_cancelled = "Tuş ataması iptal edildi."
    },
    da = {
        always_run_enabled = "Aktiver altid løb",
        utilities_server = "Server",
        always_run_menu = "Altid løb",
        always_run_description = "Når aktiveret, vil din karakter altid løbe, medmindre du holder ALT eller SHIFT for at gå.",
        always_run_capslock_hint = "Tildel en vilkårlig tast til at skifte altid løb.",
        always_run_github = "Åbn GitHub-arkiv",
        always_run_press_key_hint = "Tryk på den ønskede tast for at skifte altid løb...",
        always_run_key_selected = "Valgt tast: ",
        always_run_key = "Tast: ",
        always_run_key_cancelled = "Tildeling af tast annulleret."
    },
    nl = {
        always_run_enabled = "Altijd rennen inschakelen",
        utilities_server = "Server",
        always_run_menu = "Altijd rennen",
        always_run_description = "Wanneer ingeschakeld, rent je personage altijd, tenzij je ALT of SHIFT ingedrukt houdt om te lopen.",
        always_run_capslock_hint = "Wijs een toets toe om altijd rennen te schakelen.",
        always_run_github = "Open GitHub-repository",
        always_run_press_key_hint = "Druk op de gewenste toets om altijd rennen te schakelen...",
        always_run_key_selected = "Geselecteerde toets: ",
        always_run_key = "Toets: ",
        always_run_key_cancelled = "Toewijzing van toets geannuleerd."
    },
    no = {
        always_run_enabled = "Aktiver alltid løping",
        utilities_server = "Server",
        always_run_menu = "Alltid løping",
        always_run_description = "Når aktivert, vil karakteren din alltid løpe med mindre du holder inne ALT eller SHIFT for å gå.",
        always_run_capslock_hint = "Tildel en tast for å veksle alltid løping.",
        always_run_github = "Åpne GitHub-repositoriet",
        always_run_press_key_hint = "Trykk på ønsket tast for å veksle alltid løping...",
        always_run_key_selected = "Valgt tast: ",
        always_run_key = "Tast: ",
        always_run_key_cancelled = "Tildeling av tast avbrutt."
    },
    fi = {
        always_run_enabled = "Ota jatkuva juoksu käyttöön",
        utilities_server = "Palvelin",
        always_run_menu = "Jatkuva juoksu",
        always_run_description = "Kun tämä on käytössä, hahmosi juoksee aina, ellet pidä ALT- tai SHIFT-näppäintä painettuna kävellessäsi.",
        always_run_capslock_hint = "Aseta mikä tahansa näppäin jatkuvan juoksun vaihtamiseen.",
        always_run_github = "Avaa GitHub-repositorio",
        always_run_press_key_hint = "Paina haluamaasi näppäintä jatkuvan juoksun vaihtamiseen...",
        always_run_key_selected = "Valittu näppäin: ",
        always_run_key = "Näppäin: ",
        always_run_key_cancelled = "Näppäimen määritys peruutettu."
    },
    sv = {
        always_run_enabled = "Aktivera alltid spring",
        utilities_server = "Server",
        always_run_menu = "Alltid spring",
        always_run_description = "När aktiverat kommer din karaktär alltid att springa om du inte håller ALT eller SHIFT för att gå.",
        always_run_capslock_hint = "Tilldela valfri tangent för att växla alltid spring.",
        always_run_github = "Öppna GitHub-repo",
        always_run_press_key_hint = "Tryck på önskad tangent för att växla alltid spring...",
        always_run_key_selected = "Vald tangent: ",
        always_run_key = "Tangent: ",
        always_run_key_cancelled = "Tangenttilldelning avbröts."
    },
    cs = {
        always_run_enabled = "Povolit automatický běh",
        utilities_server = "Server",
        always_run_menu = "Automatický běh",
        always_run_description = "Když je povoleno, vaše postava bude vždy běhat, pokud nedržíte ALT nebo SHIFT pro chůzi.",
        always_run_capslock_hint = "Přiřaďte libovolnou klávesu pro přepínání automatického běhu.",
        always_run_github = "Otevřít GitHub repozitář",
        always_run_press_key_hint = "Stiskněte požadovanou klávesu pro přepnutí automatického běhu...",
        always_run_key_selected = "Vybraná klávesa: ",
        always_run_key = "Klávesa: ",
        always_run_key_cancelled = "Přiřazení klávesy zrušeno."
    },
    hu = {
        always_run_enabled = "Automatikus futás engedélyezése",
        utilities_server = "Szerver",
        always_run_menu = "Automatikus futás",
        always_run_description = "Ha engedélyezve van, a karaktered mindig futni fog, hacsak nem tartod lenyomva az ALT vagy SHIFT gombot a sétáláshoz.",
        always_run_capslock_hint = "Rendelj hozzá egy billentyűt az automatikus futás kapcsolásához.",
        always_run_github = "GitHub repó megnyitása",
        always_run_press_key_hint = "Nyomd meg a kívánt billentyűt az automatikus futás kapcsolásához...",
        always_run_key_selected = "Kiválasztott billentyű: ",
        always_run_key = "Billentyű: ",
        always_run_key_cancelled = "Billentyű hozzárendelése megszakítva."
    },
    it = {
        always_run_enabled = "Abilita corsa automatica",
        utilities_server = "Server",
        always_run_menu = "Corsa automatica",
        always_run_description = "Quando abilitato, il tuo personaggio correrà sempre a meno che tu non tenga premuto ALT o SHIFT per camminare.",
        always_run_capslock_hint = "Assegna un tasto qualsiasi per attivare/disattivare la corsa automatica.",
        always_run_github = "Apri repository GitHub",
        always_run_press_key_hint = "Premi il tasto desiderato per attivare/disattivare la corsa automatica...",
        always_run_key_selected = "Tasto selezionato: ",
        always_run_key = "Tasto: ",
        always_run_key_cancelled = "Assegnazione del tasto annullata."
    },
    uk = {
        always_run_enabled = "Увімкнути постійний біг",
        utilities_server = "Сервер",
        always_run_menu = "Постійний біг",
        always_run_description = "Коли ввімкнено, ваш персонаж завжди буде бігти, якщо ви не утримуєте ALT або SHIFT для ходьби.",
        always_run_capslock_hint = "Призначте будь-яку клавішу для перемикання автобігу.",
        always_run_github = "Відкрити GitHub репозиторій",
        always_run_press_key_hint = "Натисніть бажану клавішу для перемикання автобігу...",
        always_run_key_selected = "Клавішу вибрано: ",
        always_run_key = "Клавіша: ",
        always_run_key_cancelled = "Призначення клавіші скасовано."
    },
    th = {
        always_run_enabled = "เปิดใช้งานการวิ่งอัตโนมัติ",
        utilities_server = "เซิร์ฟเวอร์",
        always_run_menu = "การวิ่งอัตโนมัติ",
        always_run_description = "เมื่อเปิดใช้งาน ตัวละครของคุณจะวิ่งเสมอ เว้นแต่คุณจะกด ALT หรือ SHIFT เพื่อเดิน",
        always_run_capslock_hint = "กำหนดปุ่มใดก็ได้เพื่อสลับการวิ่งอัตโนมัติ",
        always_run_github = "เปิดที่เก็บ GitHub",
        always_run_press_key_hint = "กดปุ่มที่ต้องการเพื่อสลับการวิ่งอัตโนมัติ...",
        always_run_key_selected = "ปุ่มที่เลือก: ",
        always_run_key = "ปุ่ม: ",
        always_run_key_cancelled = "ยกเลิกการกำหนดปุ่มแล้ว"
    }
}